services:
  adguard:
    image: adguard/adguardhome:latest
    init: true
    container_name: adguard
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3003:80/tcp
    volumes:
      - /mnt/apps/appdata/adguard/work:/opt/adguardhome/work
      - /mnt/apps/appdata/adguard/conf:/opt/adguardhome/conf
