services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    ports:
      - 8085:8083
    volumes:
      - /mnt/apps/appdata/calibre-web:/config
      - /mnt/storage/media/ebooks:/books
