services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    init: true
    container_name: homebox
    restart: unless-stopped
    environment:
      - HBOX_AUTH_API_KEY_PEPPER=${HOMEBOX_API_KEY_PEPPER}
    ports:
      - 7745:7745
    volumes:
      - /mnt/apps/appdata/homebox:/data
