services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    init: true
    container_name: immich-server
    restart: unless-stopped
    runtime: nvidia
    mem_limit: 4g
    mem_reservation: 256m
    ports:
      - 2283:2283
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: immich
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich-redis
      UPLOAD_LOCATION: /data
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - /mnt/storage/photos/immich:/data
      - /mnt/storage/photos:/mnt/media:ro
    depends_on:
      - immich-redis
      - immich-postgres
    labels:
      - com.centurylinklabs.watchtower.enable=false

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    init: true
    container_name: immich-machine-learning
    restart: unless-stopped
    runtime: nvidia
    mem_limit: 4g
    mem_reservation: 256m
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: immich
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: immich
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - /mnt/docker-local/appdata/immich/ml-cache:/cache
    labels:
      - com.centurylinklabs.watchtower.enable=false

  immich-redis:
    image: redis:6.2-alpine
    init: true
    container_name: immich-redis
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    init: true
    container_name: immich-postgres
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 256m
    shm_size: 128mb
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_DB: immich
    volumes:
      - /mnt/apps/appdata/immich/db:/var/lib/postgresql/data
    labels:
      - com.centurylinklabs.watchtower.enable=false
