services:
  ntfy:
    image: binwiederhier/ntfy:latest
    init: true
    container_name: ntfy
    restart: unless-stopped
    command: serve
    environment:
      - TZ=America/Chicago
    volumes:
      - /mnt/apps/appdata/ntfy/config:/etc/ntfy
      - /mnt/apps/appdata/ntfy/data:/var/lib/ntfy
    ports:
      - "2586:80"
