services:
  grafana:
    image: grafana/grafana:latest
    init: true
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GRAFANA_POSTGRES_PASSWORD=${GRAFANA_POSTGRES_PASSWORD}
      - TZ=America/Chicago
    volumes:
      - /mnt/apps/appdata/grafana:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:latest
    init: true
    container_name: loki
    restart: unless-stopped
    volumes:
      - /mnt/apps/appdata/loki:/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:latest
    init: true
    container_name: alloy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /mnt/apps/appdata/alloy:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

  prometheus:
    image: prom/prometheus:latest
    init: true
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /mnt/apps/appdata/prometheus:/prometheus
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
