services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 8765:80
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=${SPEEDTEST_APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=<server-ip>
      - DB_PORT=5432
      - DB_DATABASE=speedtest
      - DB_USERNAME=speedtest
      - DB_PASSWORD=${SPEEDTEST_DB_PASSWORD}
      - SPEEDTEST_SCHEDULE=0 * * * *
      - DISPLAY_TIMEZONE=America/Chicago
    volumes:
      - /mnt/apps/appdata/speedtest-tracker:/config
