services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    init: true
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - /opt/uptime-kuma:/app/data
