services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=https://vaultwarden.${DOMAIN}
    ports:
      - 8080:80
      - 3012:3012
    volumes:
      - /mnt/apps/appdata/vaultwarden:/data
    labels:
      - com.centurylinklabs.watchtower.enable=false
